version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "lockfile-only"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      node-security:
        applies-to: security-updates
        patterns:
          - "node*"
          - "@node*"
    open-pull-requests-limit: 0
    labels:
      - "security-high"
      - "dependencies"
    commit-message:
      prefix: "security"
      include: "scope"
